options:
  logging: CLOUD_LOGGING_ONLY
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/ci-cd-practice-cloud/fastapi-app:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/ci-cd-practice-cloud/fastapi-app:latest']

images:
  - 'gcr.io/ci-cd-practice-cloud/fastapi-app:latest'